name: Build
on:
  workflow_dispatch:
jobs:
  build_ios:
    permissions:
      contents: write
    runs-on: macos-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: 'RazrFalcon/resvg'
          fetch-depth: 0

      - name: Get the latest tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Checkout latest tag
        run: git checkout ${{ env.latest_tag }}

      - name: Build c-api
        run: |
          cd crates/c-api
          rustup target add aarch64-apple-ios aarch64-apple-ios-sim aarch64-apple-darwin
          cargo build --target aarch64-apple-ios --release --no-default-features
          cargo build --target aarch64-apple-ios-sim --release --no-default-features
          cargo build --target aarch64-apple-darwin --release --no-default-features

      - name: Create xcframework
        run: |
          mkdir include
          cp crates/c-api/resvg.h include
          xcodebuild -create-xcframework \
          -library target/aarch64-apple-ios/release/libresvg.a -headers include \
          -library target/aarch64-apple-ios-sim/release/libresvg.a -headers include \
          -library target/aarch64-apple-darwin/release/libresvg.a -headers include \
          -output resvg.xcframework

      - name: Zip
        run: zip -r resvg.xcframework.zip resvg.xcframework

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.latest_tag }}
          files: resvg.xcframework.zip

  build_android:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          repository: 'RazrFalcon/resvg'
          fetch-depth: 0

      - name: Get the latest tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
      - name: Checkout latest tag
        run: git checkout ${{ env.latest_tag }}

      - name: Install Android NDK
        run: |
          wget -nv https://dl.google.com/android/repository/android-ndk-r27-linux.zip
          unzip -qq android-ndk-r27-linux.zip
          mv android-ndk-r27 android-ndk
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$(pwd)/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang" >> $GITHUB_ENV
          echo "CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER=$(pwd)/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang" >> $GITHUB_ENV

      - name: Build c-api
        run: |
          cd crates/c-api
          rustup target add aarch64-linux-android x86_64-linux-android
          cargo build --target aarch64-linux-android --config target.aarch64-linux-android.linker=\"$CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER\" --release --no-default-features
          cargo build --target x86_64-linux-android --config target.x86_64-linux-android.linker=\"$CARGO_TARGET_X86_64_LINUX_ANDROID_LINKER\" --release --no-default-features

      - name: Copy
        run: |
          mkdir -p jniLibs/arm64-v8a jniLibs/x86_64
          cp target/aarch64-linux-android/release/libresvg.so jniLibs/arm64-v8a
          cp target/x86_64-linux-android/release/libresvg.so jniLibs/x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jniLibs
          path: jniLibs
